INSERT INTO A2_OFFICERS VALUES('1','Officer1','Officer1',SYSDATE);
INSERT INTO A2_OFFICERS VALUES('2','Officer2','Officer2',SYSDATE);
INSERT INTO A2_OFFICERS VALUES('3','Officer3','Officer3',SYSDATE);
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.add_client('Nona','Mu','Paris','1','2','Nona.Mu',12000);
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.auth_client('401');
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.update_client('401','Nona','MuE','Paris','Nona.MuE',12000);
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.add_card('401','USD',1.5);
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.auth_add_card('301');
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.auth_add_card('301');
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.put_money_on_card('301',200);
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.client_card_payment('301');
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.take_money_from_card('301',100);
EXECUTE DBMS_OUTPUT.PUT_LINE(CREDIT_CARD_MANAGEMENT_SYSTEM.print_client_balance('301'));
EXECUTE CREDIT_CARD_MANAGEMENT_SYSTEM.delete_client('401');

SELECT * FROM A1_CLIENTS;
SELECT * FROM A2_OFFICERS;
SELECT * FROM A3_CREDIT_CARDS;
SELECT * FROM A4_CARD_TRANSACTIONS;


drop table A3_CREDIT_CARDS;
drop table A1_CLIENTS;
drop table A2_OFFICERS;
drop table A4_CARD_TRANSACTIONS;

